language: cpp

compiler:
    - g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y
    - sudo apt-get install -y libboost-all-dev doxygen
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -y g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
    - ./make.sh debug
    - ./make.sh release
    - ./make.sh docs
    # Install debug build. Also necessary to compile examples.
    # The `env "PATH=$PATH"` part is required so cmake is available with sudo.
    # See https://github.com/travis-ci/travis-ci/issues/1350
    - sudo env "PATH=$PATH" ./make.sh install debug
    # Compile examples.
    - echo "Compiling examples..."; set -e; for dir in examples/*/; do (cd "$dir" && ./make.sh && echo "- ${dir%*/} compiled successfully."); done
